pact-418
Ilia/docs.pactflow.io pull request #7
Opened 2022-12-05 23:33 UTC by Ilia

2022-12-05 23:51 UTC, ilia-test requested changes
This is a test, I am requesting changes!

2022-12-05 23:56 UTC, ilia-test commented on .github/workflows/jira-issue-create.yml
> +  build:
this is a test comment

2022-12-05 23:56 UTC, ilia-test requested changes

2022-12-05 23:56 UTC, ilia-test commented on .github/workflows/jira-issue-create.yml
> +        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
this is another

2022-12-06 00:23 UTC, Ilia commented
This can go back to review!

2022-12-06 00:24 UTC, Ilia commented on .github/workflows/jira-issue-create.yml
> +  build:
test

2022-12-06 00:43 UTC, Ilia commented
another comment!

2022-12-06 00:47 UTC, Ilia commented
and another!

2022-12-06 00:50 UTC, Ilia commented
this is another test

2022-12-06 00:51 UTC, Ilia commented on .github/workflows/jira-issue-create.yml
> +        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
another test as reply

2022-12-06 00:52 UTC, Ilia commented
test

2022-12-06 00:56 UTC, Ilia commented
test comment in conversation tab

2022-12-06 00:57 UTC, Ilia commented
test comment in conversation tab

2022-12-06 01:06 UTC, Ilia commented
this is a test!

2022-12-06 01:17 UTC, Ilia commented
this is a test comment!

2022-12-06 01:18 UTC, Ilia commented on .github/workflows/jira-issue-create.yml
> +  build:
hello!

2022-12-06 01:59 UTC, Ilia commented
test

2022-12-06 01:59 UTC, Ilia commented on .github/workflows/jira-issue-create.yml
> +        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
teest comment

2022-12-06 09:11 UTC, Ilia commented
/done

2022-12-06 09:14 UTC, Ilia commented
/done

2022-12-06 09:16 UTC, Ilia commented
test

2022-12-06 09:16 UTC, Ilia commented on .github/workflows/jira-issue-create.yml
> +        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
test

2022-12-06 09:17 UTC, Ilia commented
/done

2022-12-06 09:18 UTC, Ilia commented
test

2022-12-06 09:19 UTC, Ilia commented
/done

2022-12-06 09:23 UTC, Ilia commented
/done

2022-12-06 09:25 UTC, Ilia commented
/done

2022-12-06 09:33 UTC, Ilia commented
/done

2022-12-06 09:46 UTC, Ilia commented
resolves #6

2022-12-09 03:25 UTC, Ilia commented
/done

2022-12-09 03:27 UTC, merged